AccountAttr:
    type: entity
    table: Account_Attr
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        value:
            type: text
            nullable: true
        enable:
            type: boolean
            nullable: false
        original:
            type: boolean
            nullable: false
        createdat:
            type: datetime
            nullable: false
            column: createdAt
        updatedat:
            type: datetime
            nullable: false
            column: updatedAt
    manyToOne:
        account:
            targetEntity: Account
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                account_id:
                    referencedColumnName: id
            orphanRemoval: false
        accountAttrType:
            targetEntity: AccountAttrType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                account_attr_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
