Course:
    type: entity
    table: Course
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        enable:
            type: boolean
            nullable: false
        closed:
            type: boolean
            nullable: false
        createdat:
            type: datetime
            nullable: false
            column: createdAt
        updatedat:
            type: datetime
            nullable: false
            column: updatedAt
    manyToMany:
        child:
            targetEntity: Course
            cascade: {  }
            mappedBy: parent
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
