e_alps_portal:
    pattern:  /
    defaults: { _controller: eALPSPortalBundle:Default:index }
    
e_alps_portal_schedule:
    pattern:  /schedule
    defaults: { _controller: eALPSPortalBundle:Default:schedule }

e_alps_portal_schedule_admin:
    pattern:  /scheduleAdmin
    defaults: { _controller: eALPSPortalBundle:Default:scheduleAdmin }
    
e_alps_portal_schedule_admin_accountid:
    pattern:  /scheduleAdmin/{accountId}
    defaults: { _controller: eALPSPortalBundle:Default:scheduleAdminAccountId }
    
e_alps_portal_redirect_moodle_course:
    pattern:  /redirectMoodleCourse/{opYear}/{siteCode}/{titleCode}
    defaults: { _controller: eALPSPortalBundle:Redirect:redirectMoodleCourse }
    
e_alps_portal_redirect_moodle_course_info:
    pattern:  /redirectMoodleCourseInfo/{opYear}/{siteCode}/{titleCode}
    defaults: { _controller: eALPSPortalBundle:Redirect:redirectMoodleCourseInfo }
    
e_alps_portal_login_admin:
    pattern:  /login/admin
    defaults: { _controller: eALPSPortalBundle:Login:admin }
    
e_alps_portal_login_acsu_error:
    pattern:  /login/acsuError
    defaults: { _controller: eALPSPortalBundle:Login:acsuError }
    
e_alps_portal_login_citizen:
    pattern:  /login/citizen
    defaults: { _controller: eALPSPortalBundle:Login:citizen }
    
e_alps_portal_login_eches:
    pattern:  /login/eChes
    defaults: { _controller: eALPSPortalBundle:Login:eChes }

e_alps_portal_login_facility:
    pattern:  /login/facility
    defaults: { _controller: eALPSPortalBundle:Login:facility }