e_alps_portal_schedule:
    pattern:  /
    defaults: { _controller: eALPSPortalBundle:Default:index }

e_alps_portal_schedule_admin:
    pattern:  /scheduleAdmin
    defaults: { _controller: eALPSPortalBundle:Default:scheduleAdmin }
    
e_alps_portal_schedule_admin_accountid:
    pattern:  /scheduleAdmin/{accountId}
    defaults: { _controller: eALPSPortalBundle:Default:scheduleAdminAccountId }
    
e_alps_portal_login_admin:
    pattern:  /login/admin
    defaults: { _controller: eALPSPortalBundle:Login:admin }
    
e_alps_portal_login_facility:
    pattern:  /login/facility
    defaults: { _controller: eALPSPortalBundle:Login:facility }