parameters:
#    e_alps_portal.example.class: eALPS\PortalBundle\Example

services:
#    e_alps_portal.example:
#        class: %e_alps_portal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
